// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vampInfo
List vampInfo();
RcppExport SEXP _ReVAMP_vampInfo() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(vampInfo());
    return rcpp_result_gen;
END_RCPP
}
// vampPaths
StringVector vampPaths();
RcppExport SEXP _ReVAMP_vampPaths() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(vampPaths());
    return rcpp_result_gen;
END_RCPP
}
// vampPlugins
DataFrame vampPlugins();
RcppExport SEXP _ReVAMP_vampPlugins() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(vampPlugins());
    return rcpp_result_gen;
END_RCPP
}
// vampPluginParams
DataFrame vampPluginParams(std::string key);
RcppExport SEXP _ReVAMP_vampPluginParams(SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    rcpp_result_gen = Rcpp::wrap(vampPluginParams(key));
    return rcpp_result_gen;
END_RCPP
}
// runPlugin
List runPlugin(std::string key, S4 wave, Nullable<List> params, bool useFrames, Nullable<int> blockSize, Nullable<int> stepSize);
RcppExport SEXP _ReVAMP_runPlugin(SEXP keySEXP, SEXP waveSEXP, SEXP paramsSEXP, SEXP useFramesSEXP, SEXP blockSizeSEXP, SEXP stepSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< S4 >::type wave(waveSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type useFrames(useFramesSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type blockSize(blockSizeSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type stepSize(stepSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(runPlugin(key, wave, params, useFrames, blockSize, stepSize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ReVAMP_vampInfo", (DL_FUNC) &_ReVAMP_vampInfo, 0},
    {"_ReVAMP_vampPaths", (DL_FUNC) &_ReVAMP_vampPaths, 0},
    {"_ReVAMP_vampPlugins", (DL_FUNC) &_ReVAMP_vampPlugins, 0},
    {"_ReVAMP_vampPluginParams", (DL_FUNC) &_ReVAMP_vampPluginParams, 1},
    {"_ReVAMP_runPlugin", (DL_FUNC) &_ReVAMP_runPlugin, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ReVAMP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
