# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vampInfo <- function() {
    .Call(`_ReVAMP_vampInfo`)
}

vampPaths <- function() {
    .Call(`_ReVAMP_vampPaths`)
}

vampPlugins <- function() {
    .Call(`_ReVAMP_vampPlugins`)
}

vampPluginParams <- function(key) {
    .Call(`_ReVAMP_vampPluginParams`, key)
}

runPlugin <- function(key, wave, params = NULL, useFrames = FALSE, blockSize = NULL, stepSize = NULL, verbose = FALSE) {
    .Call(`_ReVAMP_runPlugin`, key, wave, params, useFrames, blockSize, stepSize, verbose)
}

