# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vampInfo <- function() {
    .Call(`_ReVAMP_vampInfo`)
}

vampPaths <- function() {
    .Call(`_ReVAMP_vampPaths`)
}

vampPlugins <- function() {
    .Call(`_ReVAMP_vampPlugins`)
}

vampParams <- function(key) {
    .Call(`_ReVAMP_vampParams`, key)
}

runPlugin <- function(key, wave, outfilename, useFrames) {
    .Call(`_ReVAMP_runPlugin`, key, wave, outfilename, useFrames)
}

rcpp_type <- function(x) {
    invisible(.Call(`_ReVAMP_rcpp_type`, x))
}

